services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: always

    env_file:
    - .env
    environment:
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    depends_on:
    - db
    ports:
    - ${API_SERVER_PORT}:5000

    command: ["poetry", "run", "uvicorn", "fastapi_template.web.application:get_app", "--host", "0.0.0.0", "--port", "5000"]

  db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile

    restart: always

    env_file:
    - .env
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
    ports:
    - ${POSTGRES_EXTERNAL_PORT}:5432
    volumes:
    - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data/pgdata

networks:
  default:
    driver: bridge
